@base_url = http://127.0.0.1:8000/api/v1

@user_id1 = 094c6c65-fa4c-4324-bb7e-c0dda9595e54

### Healthz
GET {{base_url}}/healthz

### Create User
POST {{base_url}}/users
Content-Type: application/json

{
    "email": "test3@test.com",
    "name": "Jeff Three"
}

### Get User
GET {{base_url}}/users/{{user_id1}}

### List Users
GET {{base_url}}/users