@base_url = http://127.0.0.1:8000/api/v1

@user_id1 = 8a75734d-1847-4a5a-8c10-a2dd32589438

### Healthz
GET {{base_url}}/healthz

### Create User
POST {{base_url}}/users
Content-Type: application/json

{
    "email": "test2@test.com",
    "name": "Jeff Jeffries"
}

### Get User
GET {{base_url}}/users/{{user_id1}}

