@base_url = http://127.0.0.1:8000/api/v1

@user_id1 = f990d059-ed74-4cf5-bac8-5c6e71a05c84

### Healthz
GET {{base_url}}/healthz

### Create User
POST {{base_url}}/users
Content-Type: application/json

{
    "email": "test@test.com",
    "name": "Jeff Jeffries"
}

### Get User
GET {{base_url}}/users/{{user_id1}}

