[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "zero2prod"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
config = "0.13.2"
env_logger = "0.9.3"
log = "0.4.17"
paste = "1.0.12"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version="1", features=["macros", "rt-multi-thread"] }
uuid = { version = "1.2.1", features = ["v4"] }

[dev-dependencies]
reqwest = { version = "0.11.12", features = ["json"] }
