[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "zero2prod"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
serde = { version = "1.0.147", features = ["derive"] }
tokio = {version="1", features=["macros", "rt-multi-thread"]}

[dev-dependencies]
reqwest = "0.11.12"
