[advisories]
ignore = ["RUSTSEC-2023-0071"]
informational_warnings = ["unmaintained"]
severity_threshold = "medium"             # CVSS severity ("none", "low", "medium", "high", "critical")

[target]
arch = "x86_64"
os = "linux"
