name: main-branch-check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: install protoc
        uses: arduino/setup-protoc@v1

      - name: checkout repository
        uses: actions/checkout@v3

      - name: check formatting
        run: make check-format

      - name: lint
        run: make check-lint

      - name: audit
        run: make check-audit

      - name: build
        run: make build

      - name: tests
        run: make test
